name: Build and Deploy Backend

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/mahmoudshabaan22/backend-vps:latest

jobs:

  # ==========================================
  # 1. Build Docker Image and Push to GHCR
  # ==========================================
  build-and-push:
    name: Build & Push Backend Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      # ----------------------------------------
      # Checkout source code
      # ----------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4


      # ----------------------------------------
      # Login to GitHub Container Registry
      # ----------------------------------------
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # ----------------------------------------
      # Build Docker image
      # ----------------------------------------
      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME \
            .


      # ----------------------------------------
      # Push Docker image to GHCR
      # ----------------------------------------
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME


  # ==========================================
  # 2. Deploy Backend to Self-Hosted Runner
  # ==========================================
  deploy:
    name: Deploy Backend
    needs: build-and-push

    runs-on: self-hosted

    permissions:
      contents: read
      packages: read

    steps:

      # ----------------------------------------
      # Check Docker and Docker Compose
      # ----------------------------------------
      - name: Check Docker
        run: |
          docker --version
          docker compose version


      # ----------------------------------------
      # Go to deployment directory
      # ----------------------------------------
      - name: Check deployment directory
        working-directory: /opt/myapp
        run: |
          pwd
          ls -la


      # ----------------------------------------
      # Pull the latest Backend image
      #
